<a href="https://colab.research.google.com/github/Sreelakshmiml/Natural-language-processing/blob/main/Bag_of_Words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install spacy
import spacy
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
#stemming
stemmer = PorterStemmer()
nlp = spacy.load("en_core_web_sm")
text = "It combines computational linguistics with statistical, machine learning, and deep learning models to process human language in the form of text or voice data and to ‘understand’ its full meaning"
words = word_tokenize(text)
for word in words:
  print(word,"|",stemmer.stem(word))

It | it
combines | combin
computational | comput
linguistics | linguist
with | with
statistical | statist
, | ,
machine | machin
learning | learn
, | ,
and | and
deep | deep
learning | learn
models | model
to | to
process | process
human | human
language | languag
in | in
the | the
form | form
of | of
text | text
or | or
voice | voic
data | data
and | and
to | to
‘ | ‘
understand | understand
’ | ’
its | it
full | full
meaning | mean


In [ ]:
#lemmatization
nlp = spacy.load("en_core_web_sm")
doc = nlp("It combines computational linguistics with statistical, machine learning, and deep learning models to process human language in the form of text or voice data and to ‘understand’ its full meaning")
for token in doc:
  print(token,"|",token.lemma_)

It | it
combines | combine
computational | computational
linguistics | linguistic
with | with
statistical | statistical
, | ,
machine | machine
learning | learning
, | ,
and | and
deep | deep
learning | learning
models | model
to | to
process | process
human | human
language | language
in | in
the | the
form | form
of | of
text | text
or | or
voice | voice
data | datum
and | and
to | to
‘ | '
understand | understand
’ | '
its | its
full | full
meaning | meaning


In [ ]:
#defining custom lemma of certain words
ar = nlp.get_pipe('attribute_ruler')
ar.add([[{'Text':'Sis'}],[{'Text':'Sissy'}]],{'Lemma':'Sister'})
doc = nlp("Hi Sissy, How are u Sis")
for token in doc:
  print(token.text,"|",token.lemma_)

Hi | hi
Sissy | Sister
, | ,
How | how
are | be
u | u
Sis | Sister


In [ ]:
#parts of speech
doc = nlp("This is a very recent and effective approach due to which it has a really high demand in today’s market.")
for token in doc:
  print(token,"|",token.pos_,spacy.explain(token.pos_))

This | PRON pronoun
is | AUX auxiliary
a | DET determiner
very | ADV adverb
recent | ADJ adjective
and | CCONJ coordinating conjunction
effective | ADJ adjective
approach | NOUN noun
due | ADP adposition
to | ADP adposition
which | PRON pronoun
it | PRON pronoun
has | VERB verb
a | DET determiner
really | ADV adverb
high | ADJ adjective
demand | NOUN noun
in | ADP adposition
today | NOUN noun
’s | PART particle
market | NOUN noun
. | PUNCT punctuation


Bag of words model

In [ ]:
#implementation of bow using training and testing
import pandas as pd
import numpy as np
df = pd.read_csv("/content/spam.csv")
df.head()

category                                            content
0      spam              congratulations! You have won 10 lakh
1  not spam  I just want to confirm the meeting is schedule...
2      spam  please verify your details by clicking on this...
3      spam             no experince required. Earn 5000 daily
4  not spam  please review the attached document and update...

In [ ]:
df.category.value_counts()

spam        5
not spam    5
Name: category, dtype: int64

In [ ]:
#apply lambda function
df['spam']=df['category'].apply(lambda x:1 if x=='spam' else 0)

In [ ]:
df.head()

category                                            content  spam
0      spam              congratulations! You have won 10 lakh     1
1  not spam  I just want to confirm the meeting is schedule...     0
2      spam  please verify your details by clicking on this...     1
3      spam             no experince required. Earn 5000 daily     1
4  not spam  please review the attached document and update...     0

In [ ]:
df.shape

(10, 3)

In [ ]:
#splitting dataset into test and train data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(df.content,df.spam,test_size=0.2)

In [ ]:
x_train.shape

(8,)

In [ ]:
type(x_train)

pandas.core.series.Series

In [ ]:
#transforming x_train into a matrix
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_cv= v.fit_transform(x_train.values)
x_train_cv

<8x55 sparse matrix of type '<class 'numpy.int64'>'
	with 64 stored elements in Compressed Sparse Row format>

In [ ]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
v.get_feature_names_out()[5]

'are'

In [ ]:
v.vocabulary_

{'this': 46,
 'email': 21,
 'confirms': 13,
 'the': 45,
 'invoice': 26,
 'of': 36,
 'recent': 40,
 'payment': 38,
 'congratulations': 14,
 'you': 53,
 'are': 5,
 'eligible': 20,
 'for': 23,
 'lack': 29,
 'limit': 31,
 'idfc': 25,
 'credit': 15,
 'card': 9,
 'thankyou': 44,
 'your': 54,
 'application': 4,
 'at': 6,
 'abc': 2,
 'company': 11,
 'just': 28,
 'want': 51,
 'to': 47,
 'confirm': 12,
 'meeting': 34,
 'is': 27,
 'scheduled': 43,
 'tommorrow': 48,
 'please': 39,
 'verify': 50,
 'details': 17,
 'by': 8,
 'clicking': 10,
 'on': 37,
 'link': 32,
 'review': 42,
 'attached': 7,
 'document': 18,
 'and': 3,
 'update': 49,
 'me': 33,
 'no': 35,
 'experince': 22,
 'required': 41,
 'earn': 19,
 '5000': 1,
 'daily': 16,
 'have': 24,
 'won': 52,
 '10': 0,
 'lakh': 30}

In [ ]:
x_train_np = x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#searching for non-zero element in first row
np.where(x_train_np[0]!=0)

(array([13, 21, 26, 36, 38, 40, 45, 46]),)

In [ ]:
#building model
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [ ]:
x_test_cv = v.transform(x_test)

In [ ]:
#classification report
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



tarin the model using pipeline

In [ ]:
from sklearn.pipeline import Pipeline
#creating a pipeline object
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(x_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

